language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly # ignore errors, see below

# lock distro so new future defaults will not break the build
dist: trusty

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install

script:
  - ./vendor/bin/phpunit -v --coverage-text --coverage-clover=./build/logs/clover.xml

after_script:
  - if [ -f ./build/logs/clover.xml ]; then travis_retry composer require php-coveralls/php-coveralls --no-interaction --update-with-dependencies; fi
  - if [ -f ./build/logs/clover.xml ]; then php vendor/bin/php-coveralls -v; fi
